USE world;
DROP PROCEDURE IF EXISTS lenguasEspañolas;
DELIMITER $$
CREATE PROCEDURE lenguasEspañolas()
BEGIN
	SELECT DISTINCT LANGUAGE, PERCENTAGE FROM COUNTRYLANGUAGE INNER JOIN COUNTRY
    ON CODE=COUNTRYCODE WHERE COUNTRY.NAME LIKE "SPAIN";
END$$
DELIMITER ;
CALL lenguasEspañolas();