USE world;
DROP PROCEDURE IF EXISTS poblacionEspaña;
DELIMITER $$
CREATE PROCEDURE poblacionEspaña()
BEGIN
	SELECT CO.POPULATION, SUM(CI.POPULATION) FROM COUNTRY CO INNER JOIN
    CITY CI ON CO.CODE=CI.COUNTRYCODE WHERE CO.NAME LIKE "Spain";
END$$
DELIMITER ;
CALL poblacionEspaña();