USE world;
DROP PROCEDURE IF EXISTS vascoParlantes;
DELIMITER $$
CREATE PROCEDURE vascoParlantes()
BEGIN
	SELECT CI.NAME, ROUND(CI.POPULATION*CL.PERCENTAGE/100,2) AS HABLANTES
    FROM COUNTRYLANGUAGE CL INNER JOIN CITY CI ON CL.COUNTRYCODE=CI.COUNTRYCODE 
    INNER JOIN COUNTRY CO ON CO.CODE=CI.COUNTRYCODE
    WHERE CO.NAME LIKE "SPAIN" AND CL.LANGUAGE LIKE "BASQUE";
END$$
DELIMITER ;
CALL vascoParlantes();