USE world;
DROP PROCEDURE IF EXISTS vascoParlantes2;
DELIMITER $$
CREATE PROCEDURE vascoParlantes2()
BEGIN
    DECLARE PORCIENTO REAL DEFAULT 0;
    DECLARE CODIGO VARCHAR(3) DEFAULT "";
    
    SELECT CODE INTO CODIGO FROM COUNTRY WHERE NAME LIKE "SPAIN";
	
    SELECT PERCENTAGE INTO PORCIENTO FROM COUNTRYLANGUAGE
    WHERE COUNTRYCODE LIKE CODIGO AND LANGUAGE LIKE "BASQUE";
    
    SET PORCIENTO=PORCIENTO/100;
    
    SELECT NAME, ROUND(POPULATION*PORCIENTO) AS HABLANTES
    FROM CITY WHERE COUNTRYCODE LIKE CODIGO;
END$$
DELIMITER ;
CALL vascoParlantes2();
